apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: presence-stage
nameSuffix: -stage
commonLabels:
  overlay: stage
bases:
- ../../base
- ../../postgres
images:
- name: flyway/flyway
  newName: gcr.io/adoptingerlang/flyway
  newTag: 6-alpine
- name: postgres
  newName: gcr.io/adoptingerlang/postgres
  newTag: 11-alpine
configMapGenerator:
- env: stage.env
  name: configmap
