apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: presence
commonLabels:
  app: presence
commonAnnotations:
  oncallPager: 800-555-1212
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
