{{- if .Values.monitoring.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-prometheus-rules"
  labels:
    role: prometheus-rulefiles
    prometheus: "{{ .Release.Name }}-prometheus"
data:
{{ (.Files.Glob "alert-rules/*").AsConfig | indent 2 }}
{{ end }}
