apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    tier: app
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        release: "{{ .Release.Name }}"
        tier: app
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DISCOVERY_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-presence-config"
              key: presence.discovery_domain
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-presence-config"
              key: presence.postgres_host
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-presence-config"
              key: presence.postgres_host
        - name: POSTGRES_DATABASE
          value: "{{ .Values.postgresql.postgresDatabase }}"
        - name: POSTGRES_USER
          value: "{{ .Values.postgresql.postgresUser }}"
        - name: POSTGRES_PASSWORD
          value: presence
          #valueFrom:
          #  secretKeyRef:
          #    name: "{{ .Release.Name }}-postgresql"
          #    key: postgres-password
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        #livenessProbe:
        #  httpGet:
        #    path: /
        #    port: {{ .Values.service.internalPort }}
        #readinessProbe:
        #  httpGet:
        #    path: /
        #    port: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
