apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-postgres-metrics
  labels:
    release: "{{ .Release.Name }}"
    app: presence-postgresql
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 9187
    targetPort: 9187
    protocol: TCP
    name: metrics
  selector:
    app: presence-postgresql
