{{ if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: "{{ .Release.Name }}-service-monitor-pg"
  labels:
    tier: app
    release: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app: presence-postgresql
  endpoints:
  - port: pgmetrics
    interval: 10s
{{ end }}
