replicaCount: 1
image:
  repository: tsloughter/presence
  tag: stable
  pullPolicy: Always
service:
  name: presence
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

monitoring:
  enabled: true

postgresql:
  metrics:
    enabled: true
  postgresUser: presence
  postgresDatabase: presence
  postgresPassword: presence
  enabled: true

prometheus-operator:
  enabled: true
  rbacEnable: false

kube-prometheus:
  rbacEnable: false
